CapaPresentacion/Controllers/ClienteController.cs
using CapaEntidad;
using CapaNegocio;
using System.Collections.Generic;
using System.Web.Mvc;

namespace CapaPresentacion.Controllers
{
    public class ClienteController : Controller
    {
        readonly NegocioCliente negocioCliente = new NegocioCliente();
        // GET: Cliente
        public ActionResult Index()
        {
            return View(negocioCliente.Mostar());
        }

        // GET: Cliente/Create
        public ActionResult Create()
        {
            var list = negocioCliente.ListaCategoria();

            List<SelectListItem> items = list.ConvertAll(a =>
            {
                return new SelectListItem()
                {
                    Text = a.Nombre,
                    Value = a.ID.ToString(),
                    Selected = true
                };
            });

            ViewBag.items = items;


            return View();
        }

        // POST: Cliente/Create
        [HttpPost]
        public ActionResult Create(Cliente cliente)
        {
            try
            {
                // TODO: Add insert logic here

                negocioCliente.Guardar(cliente);

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Cliente/Edit/5
        public ActionResult Edit(int id)
        {
            var list = negocioCliente.ListaCategoria();

            List<SelectListItem> items = list.ConvertAll(a =>
            {
                return new SelectListItem()
                {
                    Text = a.Nombre,
                    Value = a.ID.ToString(),
                    Selected = true
                };
            });

            ViewBag.items = items;
            var model = negocioCliente.Buscar(id);

            return View(model);
        }

        // POST: Cliente/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, Cliente cliente)
        {
            try
            {
                // TODO: Add update logic here

                negocioCliente.Actualizar(cliente);


                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Cliente/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Cliente/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, Cliente cliente)
        {
            try
            {
                // TODO: Add delete logic here

                negocioCliente.Eliminar(cliente);


                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

CapaPresentacion/Views/Cliente/Create.cshtml
@model CapaEntidad.Cliente

@{
    ViewBag.Title = "Create";

    List<SelectListItem> items = (List<SelectListItem>)ViewBag.items;
}

<h2 class="my-2 text-center text-uppercase">Agregar Cliente</h2>


<div class="row justify-content-center">
    <div class="col-12 col-md-8 text-center">
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group">
                    <div class="col">
                        @Html.EditorFor(model => model.RncCedula, new { htmlAttributes = new { @class = "form-control", placeholder = "RNC o Cedula" } })
                        @Html.ValidationMessageFor(model => model.RncCedula, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <div class="col">
                        @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control", placeholder = "Nombre" } })
                        @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <div class="col">
                        @Html.EditorFor(model => model.Telefono, new { htmlAttributes = new { @class = "form-control", placeholder = "Telefono" } })
                        @Html.ValidationMessageFor(model => model.Telefono, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <div class="col">
                        @Html.EditorFor(model => model.Correo, new { htmlAttributes = new { @class = "form-control", placeholder = "Correo" } })
                        @Html.ValidationMessageFor(model => model.Correo, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <div class="col">
                        @Html.DropDownListFor(model => model.Categoria, items, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.Categoria, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <div class="col">
                        <input type="submit" value="Guardar" class="btn btn-primary btn-block mb-2" />
                    </div>
                    <div class="col">
                        <a href="/Cliente/Index" class="btn btn-outline-dark btn-block">Volver</a>
                    </div>
                </div>
            </div>
        }
    </div>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

CapaPresentacion/Views/Cliente/Delete.cshtml
@model CapaEntidad.Cliente

@{
    ViewBag.Title = "Delete";
}

<h2 class="mt-3 text-center text-uppercase">¿Está seguro de eliminar este Cliente?</h2>

<div class="row justify-content-center mt-5">
    <div class="col-12 col-md-8 text-center">
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-actions no-color">
                <input type="submit" value="Eliminar" class="btn btn-danger btn-block mb-2" />
                <a href="/Cliente/Index" class="btn btn-outline-dark btn-block">Volver</a>
            </div>
        }
    </div>
</div>

CapaPresentacion/Views/Cliente/Edit.cshtml
@model CapaEntidad.Cliente

@{
    ViewBag.Title = "Edit";

    List<SelectListItem> items = (List<SelectListItem>)ViewBag.items;
}

<h2 class="my-2 text-center text-uppercase">Editar Cliente</h2>

<div class="row justify-content-center">
    <div class="col-12 col-md-8 text-center">

        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                @Html.HiddenFor(model => model.ID)
                <div class="form-group">
                    <div class="col">
                        @Html.EditorFor(model => model.RncCedula, new { htmlAttributes = new { @class = "form-control", placeholder = "RNC o Cedula" } })
                        @Html.ValidationMessageFor(model => model.RncCedula, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <div class="col">
                        @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control", placeholder = "Nombre" } })
                        @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <div class="col">
                        @Html.EditorFor(model => model.Telefono, new { htmlAttributes = new { @class = "form-control", placeholder = "Telefono" } })
                        @Html.ValidationMessageFor(model => model.Telefono, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <div class="col">
                        @Html.EditorFor(model => model.Correo, new { htmlAttributes = new { @class = "form-control", placeholder = "Correo" } })
                        @Html.ValidationMessageFor(model => model.Correo, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <div class="col">
                        @Html.DropDownListFor(model => model.Categoria, items, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.Categoria, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <div class="col">
                        <input type="submit" value="Actualizar" class="btn btn-success btn-block mb-2" />
                    </div>
                    <div class="col">
                        <a href="/Cliente/Index" class="btn btn-outline-dark btn-block">Volver</a>
                    </div>
                </div>
            </div>
        }
    </div>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

CapaPresentacion/Views/Cliente/Index.cshtml
@model IEnumerable<CapaEntidad.VistaClientes_Result>

@{
    ViewBag.Title = "Index";
}

<h2 class="mt-3 text-center text-uppercase">Clientes</h2>

<a href="/Cliente/Create" class="btn btn-primary my-3 btn-lg btn-block">Agregar Cliente</a>

<table class="table table-bordered table-hover">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.RncCedula)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Nombre)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Telefono)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Correo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Categoria)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.RncCedula)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Nombre)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Telefono)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Correo)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Categoria)
                </td>
                <td>
                    <a href="@Url.Action("Edit", "Cliente")/@item.ID" class="btn btn-success ml-1">
                        <i class="fa fa-pencil"></i>
                    </a>
                    <a href="@Url.Action("Delete", "Cliente")/@item.ID" class="btn btn-danger ml-1">
                        <i class="fa fa-trash"></i>
                    </a>
                </td>
            </tr>
        }

    </tbody>
</table>

@section scripts{

    <script>

        $(document).ready(function () {
            $(".table").DataTable({
                language: {
                    processing: "Procesando...",
                    lengthMenu: "Mostrar _MENU_ registros",
                    zeroRecords: "No se encontraron resultados",
                    emptyTable: "Ningún dato disponible en esta tabla",
                    infoEmpty: "Mostrando registros del 0 al 0 de un total de 0 registros",
                    infoFiltered: "(filtrado de un total de _MAX_ registros)",
                    search: "Buscar:",
                    infoThousands: ",",
                    loadingRecords: "Cargando...",
                    paginate: {
                        first: "Primero",
                        last: "Último",
                        next: "Siguiente",
                        previous: "Anterior",
                    },
                    aria: {
                        sortAscending: ": Activar para ordenar la columna de manera ascendente",
                        sortDescending:
                            ": Activar para ordenar la columna de manera descendente",
                    },
                    buttons: {
                        copy: "Copiar",
                        colvis: "Visibilidad",
                        collection: "Colección",
                        colvisRestore: "Restaurar visibilidad",
                        copyKeys:
                            "Presione ctrl o u2318 + C para copiar los datos de la tabla al portapapeles del sistema. <br /> <br /> Para cancelar, haga clic en este mensaje o presione escape.",
                        copySuccess: {
                            1: "Copiada 1 fila al portapapeles",
                            _: "Copiadas %d fila al portapapeles",
                        },
                        copyTitle: "Copiar al portapapeles",
                        csv: "CSV",
                        excel: "Excel",
                        pageLength: {
                            "-1": "Mostrar todas las filas",
                            1: "Mostrar 1 fila",
                            _: "Mostrar %d filas",
                        },
                        pdf: "PDF",
                        print: "Imprimir",
                    },
                    autoFill: {
                        cancel: "Cancelar",
                        fill: "Rellene todas las celdas con <i>%d</i>",
                        fillHorizontal: "Rellenar celdas horizontalmente",
                        fillVertical: "Rellenar celdas verticalmentemente",
                    },
                    decimal: ",",
                    searchBuilder: {
                        add: "Añadir condición",
                        button: {
                            0: "Constructor de búsqueda",
                            _: "Constructor de búsqueda (%d)",
                        },
                        clearAll: "Borrar todo",
                        condition: "Condición",
                        conditions: {
                            date: {
                                after: "Despues",
                                before: "Antes",
                                between: "Entre",
                                empty: "Vacío",
                                equals: "Igual a",
                                notBetween: "No entre",
                                notEmpty: "No Vacio",
                                not: "Diferente de",
                            },
                            number: {
                                between: "Entre",
                                empty: "Vacio",
                                equals: "Igual a",
                                gt: "Mayor a",
                                gte: "Mayor o igual a",
                                lt: "Menor que",
                                lte: "Menor o igual que",
                                notBetween: "No entre",
                                notEmpty: "No vacío",
                                not: "Diferente de",
                            },
                            string: {
                                contains: "Contiene",
                                empty: "Vacío",
                                endsWith: "Termina en",
                                equals: "Igual a",
                                notEmpty: "No Vacio",
                                startsWith: "Empieza con",
                                not: "Diferente de",
                            },
                            array: {
                                not: "Diferente de",
                                equals: "Igual",
                                empty: "Vacío",
                                contains: "Contiene",
                                notEmpty: "No Vacío",
                                without: "Sin",
                            },
                        },
                        data: "Data",
                        deleteTitle: "Eliminar regla de filtrado",
                        leftTitle: "Criterios anulados",
                        logicAnd: "Y",
                        logicOr: "O",
                        rightTitle: "Criterios de sangría",
                        title: {
                            0: "Constructor de búsqueda",
                            _: "Constructor de búsqueda (%d)",
                        },
                        value: "Valor",
                    },
                    searchPanes: {
                        clearMessage: "Borrar todo",
                        collapse: {
                            0: "Paneles de búsqueda",
                            _: "Paneles de búsqueda (%d)",
                        },
                        count: "{total}",
                        countFiltered: "{shown} ({total})",
                        emptyPanes: "Sin paneles de búsqueda",
                        loadMessage: "Cargando paneles de búsqueda",
                        title: "Filtros Activos - %d",
                    },
                    select: {
                        1: "%d fila seleccionada",
                        _: "%d filas seleccionadas",
                        cells: {
                            1: "1 celda seleccionada",
                            _: "$d celdas seleccionadas",
                        },
                        columns: {
                            1: "1 columna seleccionada",
                            _: "%d columnas seleccionadas",
                        },
                    },
                    thousands: ".",
                    datetime: {
                        previous: "Anterior",
                        next: "Proximo",
                        hours: "Horas",
                        minutes: "Minutos",
                        seconds: "Segundos",
                        unknown: "-",
                        amPm: ["am", "pm"],
                    },
                    editor: {
                        close: "Cerrar",
                        create: {
                            button: "Nuevo",
                            title: "Crear Nuevo Registro",
                            submit: "Crear",
                        },
                        edit: {
                            button: "Editar",
                            title: "Editar Registro",
                            submit: "Actualizar",
                        },
                        remove: {
                            button: "Eliminar",
                            title: "Eliminar Registro",
                            submit: "Eliminar",
                            confirm: {
                                _: "¿Está seguro que desea eliminar %d filas?",
                                1: "¿Está seguro que desea eliminar 1 fila?",
                            },
                        },
                        error: {
                            system:
                                'Ha ocurrido un error en el sistema (<a target="\\" rel="\\ nofollow" href="\\">Más información&lt;\\/a&gt;).</a>',
                        },
                        multi: {
                            title: "Múltiples Valores",
                            info: "Los elementos seleccionados contienen diferentes valores para este registro. Para editar y establecer todos los elementos de este registro con el mismo valor, hacer click o tap aquí, de lo contrario conservarán sus valores individuales.",
                            restore: "Deshacer Cambios",
                            noMulti:
                                "Este registro puede ser editado individualmente, pero no como parte de un grupo.",
                        },
                    },
                    info: "Mostrando de _START_ a _END_ de _TOTAL_ entradas",
                },
            });
        });
    </script>

}